// Generated by gencpp from file mpc/msgMPC.msg
// DO NOT EDIT!


#ifndef MPC_MESSAGE_MSGMPC_H
#define MPC_MESSAGE_MSGMPC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mpc
{
template <class ContainerAllocator>
struct msgMPC_
{
  typedef msgMPC_<ContainerAllocator> Type;

  msgMPC_()
    : phi(0.0)
    , theta(0.0)
    , psi(0.0)
    , thrust(0.0)
    , controlflag(0)  {
    }
  msgMPC_(const ContainerAllocator& _alloc)
    : phi(0.0)
    , theta(0.0)
    , psi(0.0)
    , thrust(0.0)
    , controlflag(0)  {
    }



   typedef double _phi_type;
  _phi_type phi;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _psi_type;
  _psi_type psi;

   typedef double _thrust_type;
  _thrust_type thrust;

   typedef int8_t _controlflag_type;
  _controlflag_type controlflag;




  typedef boost::shared_ptr< ::mpc::msgMPC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mpc::msgMPC_<ContainerAllocator> const> ConstPtr;

}; // struct msgMPC_

typedef ::mpc::msgMPC_<std::allocator<void> > msgMPC;

typedef boost::shared_ptr< ::mpc::msgMPC > msgMPCPtr;
typedef boost::shared_ptr< ::mpc::msgMPC const> msgMPCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mpc::msgMPC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mpc::msgMPC_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mpc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mpc': ['/home/formation/catkin_ws/src/mpc/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mpc::msgMPC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpc::msgMPC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpc::msgMPC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpc::msgMPC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc::msgMPC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc::msgMPC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mpc::msgMPC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71696ac0d5bc75bed22942029948a6b9";
  }

  static const char* value(const ::mpc::msgMPC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71696ac0d5bc75beULL;
  static const uint64_t static_value2 = 0xd22942029948a6b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::mpc::msgMPC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mpc/msgMPC";
  }

  static const char* value(const ::mpc::msgMPC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mpc::msgMPC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 phi\n\
float64 theta\n\
float64 psi\n\
float64 thrust\n\
\n\
int8 controlflag\n\
";
  }

  static const char* value(const ::mpc::msgMPC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mpc::msgMPC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.phi);
      stream.next(m.theta);
      stream.next(m.psi);
      stream.next(m.thrust);
      stream.next(m.controlflag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct msgMPC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mpc::msgMPC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mpc::msgMPC_<ContainerAllocator>& v)
  {
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "psi: ";
    Printer<double>::stream(s, indent + "  ", v.psi);
    s << indent << "thrust: ";
    Printer<double>::stream(s, indent + "  ", v.thrust);
    s << indent << "controlflag: ";
    Printer<int8_t>::stream(s, indent + "  ", v.controlflag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MPC_MESSAGE_MSGMPC_H
