// Generated by gencpp from file estimate/msgCrazyflie_imu.msg
// DO NOT EDIT!


#ifndef ESTIMATE_MESSAGE_MSGCRAZYFLIE_IMU_H
#define ESTIMATE_MESSAGE_MSGCRAZYFLIE_IMU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace estimate
{
template <class ContainerAllocator>
struct msgCrazyflie_imu_
{
  typedef msgCrazyflie_imu_<ContainerAllocator> Type;

  msgCrazyflie_imu_()
    : imu_msg(0.0)  {
    }
  msgCrazyflie_imu_(const ContainerAllocator& _alloc)
    : imu_msg(0.0)  {
    }



   typedef float _imu_msg_type;
  _imu_msg_type imu_msg;




  typedef boost::shared_ptr< ::estimate::msgCrazyflie_imu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::estimate::msgCrazyflie_imu_<ContainerAllocator> const> ConstPtr;

}; // struct msgCrazyflie_imu_

typedef ::estimate::msgCrazyflie_imu_<std::allocator<void> > msgCrazyflie_imu;

typedef boost::shared_ptr< ::estimate::msgCrazyflie_imu > msgCrazyflie_imuPtr;
typedef boost::shared_ptr< ::estimate::msgCrazyflie_imu const> msgCrazyflie_imuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::estimate::msgCrazyflie_imu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::estimate::msgCrazyflie_imu_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace estimate

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'estimate': ['/home/formation/catkin_ws/src/estimate/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::estimate::msgCrazyflie_imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::estimate::msgCrazyflie_imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::estimate::msgCrazyflie_imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::estimate::msgCrazyflie_imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::estimate::msgCrazyflie_imu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::estimate::msgCrazyflie_imu_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::estimate::msgCrazyflie_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b709b46dc338f97917b3e18f3e2367ba";
  }

  static const char* value(const ::estimate::msgCrazyflie_imu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb709b46dc338f979ULL;
  static const uint64_t static_value2 = 0x17b3e18f3e2367baULL;
};

template<class ContainerAllocator>
struct DataType< ::estimate::msgCrazyflie_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "estimate/msgCrazyflie_imu";
  }

  static const char* value(const ::estimate::msgCrazyflie_imu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::estimate::msgCrazyflie_imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 imu_msg\n\
";
  }

  static const char* value(const ::estimate::msgCrazyflie_imu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::estimate::msgCrazyflie_imu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imu_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct msgCrazyflie_imu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::estimate::msgCrazyflie_imu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::estimate::msgCrazyflie_imu_<ContainerAllocator>& v)
  {
    s << indent << "imu_msg: ";
    Printer<float>::stream(s, indent + "  ", v.imu_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESTIMATE_MESSAGE_MSGCRAZYFLIE_IMU_H
