// Generated by gencpp from file mpc/msgMPC_Data.msg
// DO NOT EDIT!


#ifndef MPC_MESSAGE_MSGMPC_DATA_H
#define MPC_MESSAGE_MSGMPC_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mpc
{
template <class ContainerAllocator>
struct msgMPC_Data_
{
  typedef msgMPC_Data_<ContainerAllocator> Type;

  msgMPC_Data_()
    : xPos(0.0)
    , yPos(0.0)
    , zPos(0.0)
    , controlFlag(0)
    , xPosRef(0.0)
    , yPosRef(0.0)
    , zPosRef(0.0)  {
    }
  msgMPC_Data_(const ContainerAllocator& _alloc)
    : xPos(0.0)
    , yPos(0.0)
    , zPos(0.0)
    , controlFlag(0)
    , xPosRef(0.0)
    , yPosRef(0.0)
    , zPosRef(0.0)  {
  (void)_alloc;
    }



   typedef double _xPos_type;
  _xPos_type xPos;

   typedef double _yPos_type;
  _yPos_type yPos;

   typedef double _zPos_type;
  _zPos_type zPos;

   typedef int8_t _controlFlag_type;
  _controlFlag_type controlFlag;

   typedef double _xPosRef_type;
  _xPosRef_type xPosRef;

   typedef double _yPosRef_type;
  _yPosRef_type yPosRef;

   typedef double _zPosRef_type;
  _zPosRef_type zPosRef;




  typedef boost::shared_ptr< ::mpc::msgMPC_Data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mpc::msgMPC_Data_<ContainerAllocator> const> ConstPtr;

}; // struct msgMPC_Data_

typedef ::mpc::msgMPC_Data_<std::allocator<void> > msgMPC_Data;

typedef boost::shared_ptr< ::mpc::msgMPC_Data > msgMPC_DataPtr;
typedef boost::shared_ptr< ::mpc::msgMPC_Data const> msgMPC_DataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mpc::msgMPC_Data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mpc::msgMPC_Data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mpc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mpc': ['/home/loic_dubois/Documents/pdm_crazyflie/catkin/src/mpc/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mpc::msgMPC_Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpc::msgMPC_Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpc::msgMPC_Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpc::msgMPC_Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc::msgMPC_Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpc::msgMPC_Data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mpc::msgMPC_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6bc2414c1027b318ae658fa2e1750a8e";
  }

  static const char* value(const ::mpc::msgMPC_Data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6bc2414c1027b318ULL;
  static const uint64_t static_value2 = 0xae658fa2e1750a8eULL;
};

template<class ContainerAllocator>
struct DataType< ::mpc::msgMPC_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mpc/msgMPC_Data";
  }

  static const char* value(const ::mpc::msgMPC_Data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mpc::msgMPC_Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 xPos\n\
float64 yPos\n\
float64 zPos\n\
\n\
int8   controlFlag\n\
\n\
float64 xPosRef\n\
float64 yPosRef\n\
float64 zPosRef\n\
";
  }

  static const char* value(const ::mpc::msgMPC_Data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mpc::msgMPC_Data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xPos);
      stream.next(m.yPos);
      stream.next(m.zPos);
      stream.next(m.controlFlag);
      stream.next(m.xPosRef);
      stream.next(m.yPosRef);
      stream.next(m.zPosRef);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct msgMPC_Data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mpc::msgMPC_Data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mpc::msgMPC_Data_<ContainerAllocator>& v)
  {
    s << indent << "xPos: ";
    Printer<double>::stream(s, indent + "  ", v.xPos);
    s << indent << "yPos: ";
    Printer<double>::stream(s, indent + "  ", v.yPos);
    s << indent << "zPos: ";
    Printer<double>::stream(s, indent + "  ", v.zPos);
    s << indent << "controlFlag: ";
    Printer<int8_t>::stream(s, indent + "  ", v.controlFlag);
    s << indent << "xPosRef: ";
    Printer<double>::stream(s, indent + "  ", v.xPosRef);
    s << indent << "yPosRef: ";
    Printer<double>::stream(s, indent + "  ", v.yPosRef);
    s << indent << "zPosRef: ";
    Printer<double>::stream(s, indent + "  ", v.zPosRef);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MPC_MESSAGE_MSGMPC_DATA_H
