(cl:in-package mpc-msg)
(cl:export '(XPOS-VAL
          XPOS
          YPOS-VAL
          YPOS
          ZPOS-VAL
          ZPOS
          SW-VAL
          SW
          XPOS_REF-VAL
          XPOS_REF
          YPOS_REF-VAL
          YPOS_REF
          ZPOS_REF-VAL
          ZPOS_REF
          XVEL-VAL
          XVEL
          YVEL-VAL
          YVEL
          ZVEL-VAL
          ZVEL
          PHI-VAL
          PHI
          THETA-VAL
          THETA
          PSI-VAL
          PSI
          THRUST-VAL
          THRUST
          XPOS_OBS-VAL
          XPOS_OBS
          YPOS_OBS-VAL
          YPOS_OBS
          ZPOS_OBS-VAL
          ZPOS_OBS
))