(cl:defpackage crazyflie_driver-srv
  (:use )
  (:export
   "ADDCRAZYFLIE"
   "<ADDCRAZYFLIE-REQUEST>"
   "ADDCRAZYFLIE-REQUEST"
   "<ADDCRAZYFLIE-RESPONSE>"
   "ADDCRAZYFLIE-RESPONSE"
   "UPDATEPARAMS"
   "<UPDATEPARAMS-REQUEST>"
   "UPDATEPARAMS-REQUEST"
   "<UPDATEPARAMS-RESPONSE>"
   "UPDATEPARAMS-RESPONSE"
  ))

