// Generated by gencpp from file beginner_tutorials/msgCrazyflie_data.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MSGCRAZYFLIE_DATA_H
#define BEGINNER_TUTORIALS_MESSAGE_MSGCRAZYFLIE_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct msgCrazyflie_data_
{
  typedef msgCrazyflie_data_<ContainerAllocator> Type;

  msgCrazyflie_data_()
    : imu_msg()
    , vrpn_msg()  {
    }
  msgCrazyflie_data_(const ContainerAllocator& _alloc)
    : imu_msg(_alloc)
    , vrpn_msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _imu_msg_type;
  _imu_msg_type imu_msg;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _vrpn_msg_type;
  _vrpn_msg_type vrpn_msg;




  typedef boost::shared_ptr< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> const> ConstPtr;

}; // struct msgCrazyflie_data_

typedef ::beginner_tutorials::msgCrazyflie_data_<std::allocator<void> > msgCrazyflie_data;

typedef boost::shared_ptr< ::beginner_tutorials::msgCrazyflie_data > msgCrazyflie_dataPtr;
typedef boost::shared_ptr< ::beginner_tutorials::msgCrazyflie_data const> msgCrazyflie_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/loic_dubois/Documents/pdm_crazyflie/catkin/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6af109ec49fecf2fd5c4a5b152fa11fb";
  }

  static const char* value(const ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6af109ec49fecf2fULL;
  static const uint64_t static_value2 = 0xd5c4a5b152fa11fbULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/msgCrazyflie_data";
  }

  static const char* value(const ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] imu_msg\n\
float32[] vrpn_msg\n\
";
  }

  static const char* value(const ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imu_msg);
      stream.next(m.vrpn_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct msgCrazyflie_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::msgCrazyflie_data_<ContainerAllocator>& v)
  {
    s << indent << "imu_msg[]" << std::endl;
    for (size_t i = 0; i < v.imu_msg.size(); ++i)
    {
      s << indent << "  imu_msg[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.imu_msg[i]);
    }
    s << indent << "vrpn_msg[]" << std::endl;
    for (size_t i = 0; i < v.vrpn_msg.size(); ++i)
    {
      s << indent << "  vrpn_msg[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vrpn_msg[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MSGCRAZYFLIE_DATA_H
