(cl:defpackage crazyflie_driver-srv
  (:use )
  (:export
   "ADDCRAZYFLIE"
   "<ADDCRAZYFLIE-REQUEST>"
   "ADDCRAZYFLIE-REQUEST"
   "<ADDCRAZYFLIE-RESPONSE>"
   "ADDCRAZYFLIE-RESPONSE"
   "REMOVECRAZYFLIE"
   "<REMOVECRAZYFLIE-REQUEST>"
   "REMOVECRAZYFLIE-REQUEST"
   "<REMOVECRAZYFLIE-RESPONSE>"
   "REMOVECRAZYFLIE-RESPONSE"
   "UPDATEPARAMS"
   "<UPDATEPARAMS-REQUEST>"
   "UPDATEPARAMS-REQUEST"
   "<UPDATEPARAMS-RESPONSE>"
   "UPDATEPARAMS-RESPONSE"
  ))

